[build]
rustflags = [
    "--remap-path-prefix=/user_path/Projects/nekoton_flutter/rust=src",
    "--remap-path-prefix=/user_path/.cargo=cargo",
    "--remap-path-prefix=/user_path/.rustup=rustup",
]

[target.aarch64-linux-android]
rustflags = [ "-C", "link-arg=-Wl,--hash-style=both" ]

[target.armv7-linux-androideabi]
rustflags = [ "-C", "link-arg=-Wl,--hash-style=both" ]

[target.i686-linux-android]
rustflags = [ "-C", "link-arg=-Wl,--hash-style=both" ]

[target.x86_64-linux-android]
rustflags = [ "-C", "link-arg=-Wl,--hash-style=both" ]
