name: nekoton_flutter_example
description: Demonstrates how to use the nekoton_flutter plugin

publish_to: "none"

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.3.0"

dependencies:
  async: ^2.9.0
  bloc: ^8.1.0
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  hex: ^0.2.0
  http: ^0.13.5
  nekoton_flutter:
    path: ../
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.10.0

flutter:
  uses-material-design: true
