name: nekoton_flutter_example
description: Demonstrates how to use the nekoton_flutter plugin.

publish_to: 'none'

environment:
  sdk: '>=2.15.1 <3.0.0'
  flutter: '>=2.8.1'

dependencies:
  cupertino_icons: ^1.0.4
  flutter:
    sdk: flutter
  nekoton_flutter:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.8.1

flutter:
  uses-material-design: true
