name: nekoton_flutter
description: Flutter plugin for TON wallets core
version: 0.2.0
homepage: 'https://github.com/broxus/nekoton-flutter'

environment:
  sdk: '>=2.13.0 <3.0.0'
  flutter: '>=2.2.0'

dependencies:
  ffi: ^1.0.0
  flutter:
    sdk: flutter
  freezed_annotation: ^1.0.0
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  json_annotation: ^4.3.0
  logger: ^1.0.0
  path_provider: ^2.0.6
  recase: ^4.0.0
  rxdart: ^0.27.0
  synchronized: ^3.0.0
  tuple: ^2.0.0

dev_dependencies:
  build_runner: ^2.0.3
  ffigen: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^1.0.0
  hive_generator: ^1.1.1
  json_serializable: ^6.0.1
  lint: ^1.5.3

flutter:
  plugin:
    platforms:
      android:
        package: com.broxus.nekoton_flutter
        pluginClass: NekotonFlutterPlugin
      ios:
        pluginClass: NekotonFlutterPlugin

  assets:
    - assets/
    - assets/js/

ffigen:
  name: 'Bindings'
  description: 'Generated bindings'
  output: 'lib/src/bindings.g.dart'
  headers:
    entry-points:
      - 'rust/target/bindings.h'
