name: nekoton_flutter
description: Flutter plugin for TON wallets core
version: 0.0.1
homepage: "https://github.com/broxus/nekoton-flutter"

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=3.0.3"

dependencies:
  args: ^2.3.1
  async: ^2.8.2
  ffi: ^2.0.0
  flutter:
    sdk: flutter
  freezed_annotation: ^2.0.3
  json_annotation: ^4.5.0
  rxdart: ^0.27.4
  tuple: ^2.0.0

dev_dependencies:
  build_runner: ^2.1.11
  ffigen: ^6.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0
  lint: ^1.8.2

flutter:
  plugin:
    platforms:
      android:
        package: com.broxus.nekoton_flutter
        pluginClass: NekotonFlutterPlugin
      ios:
        pluginClass: NekotonFlutterPlugin
      linux:
        pluginClass: NekotonFlutterPlugin
      macos:
        pluginClass: NekotonFlutterPlugin
      windows:
        pluginClass: NekotonFlutterPluginCApi

  assets:
    - assets/
    - assets/js/

ffigen:
  name: "Bindings"
  description: "Generated bindings"
  output: "lib/src/bindings.ffigen.dart"
  llvm-path:
    - "/opt/homebrew/opt/llvm"
  headers:
    entry-points:
      - "rust/target/bindings.h"
  functions:
    symbol-address:
      include:
        - ".*_free_ptr"
