name: nekoton_flutter
description: Flutter plugin for TON wallets core
version: 0.2.0
homepage: 'https://github.com/broxus/nekoton-flutter'

environment:
  sdk: '>=2.15.1 <3.0.0'
  flutter: '>=2.8.1'

dependencies:
  ffi: ^1.1.2
  flutter:
    sdk: flutter
  freezed_annotation: ^1.1.0
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  json_annotation: ^4.4.0
  logger: ^1.1.0
  path_provider: ^2.0.9
  recase: ^4.0.0
  rxdart: ^0.27.3
  synchronized: ^3.0.0
  tuple: ^2.0.0

dev_dependencies:
  build_runner: ^2.1.7
  ffigen: ^4.1.3
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1
  hive_generator: ^1.1.2
  json_serializable: ^6.1.4
  lint: ^1.8.2

flutter:
  plugin:
    platforms:
      android:
        package: com.broxus.nekoton_flutter
        pluginClass: NekotonFlutterPlugin
      ios:
        pluginClass: NekotonFlutterPlugin

  assets:
    - assets/
    - assets/js/

ffigen:
  name: 'Bindings'
  description: 'Generated bindings'
  output: 'lib/src/bindings.g.dart'
  headers:
    entry-points:
      - 'rust/target/bindings.h'
