name: nekoton_flutter
description: Flutter plugin for TON wallets core
version: 0.2.0
homepage: "https://github.com/broxus/nekoton-flutter"

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  async: ^2.8.2
  collection: ^1.16.0
  ffi: ^1.2.1
  flutter:
    sdk: flutter
  freezed_annotation: ^2.0.3
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  json_annotation: ^4.5.0
  logger: ^1.1.0
  rxdart: ^0.27.3
  synchronized: ^3.0.0+2
  tuple: ^2.0.0

dev_dependencies:
  build_runner: ^2.1.11
  ffigen: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  hive_generator: ^1.1.3
  json_serializable: ^6.2.0
  lint: ^1.8.2

flutter:
  plugin:
    platforms:
      android:
        package: com.broxus.nekoton_flutter
        pluginClass: NekotonFlutterPlugin
      ios:
        pluginClass: NekotonFlutterPlugin

  assets:
    - assets/
    - assets/js/

ffigen:
  name: "Bindings"
  description: "Generated bindings"
  output: "lib/src/bindings.g.dart"
  llvm-path:
    - "/opt/homebrew/opt/llvm"
  headers:
    entry-points:
      - "rust/target/bindings.h"
