[package]
authors = [
  "Vadim Ledyaev <vl@pmobi.tech>",
]
edition = "2018"
name = "nekoton-flutter"
version = "0.1.0"

[lib]
crate-type = ["staticlib", "cdylib"]
name = "nekoton_flutter"

[dependencies]
allo-isolate = "0.1.7"
anyhow = "1.0"
async-trait = "0.1"
base64 = "0.13"
dyn-clone = "1.0"
ed25519-dalek = "1.0"
hex = "0.4"
lazy_static = "1.4"
nekoton = {git = "https://github.com/broxus/nekoton.git", features = ["gql_transport"]}
nekoton-abi = {git = "https://github.com/broxus/nekoton.git"}
nekoton-contracts = {git = "https://github.com/broxus/nekoton.git"}
nekoton-depool = {git = "https://git.pmobi.tech/plugins/nekoton-depool.git"}
nekoton-derive = {git = "https://github.com/broxus/nekoton.git"}
nekoton-utils = {git = "https://github.com/broxus/nekoton.git"}
openssl = {version = "0.10", features = ["vendored"]}
secstr = "0.4.0"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
tokio = {version = "0.2", features = ["full"]}
ton_abi = {git = "https://github.com/broxus/ton-labs-abi.git"}
ton_block = {git = "https://github.com/broxus/ton-labs-block.git"}
ton_types = {git = "https://github.com/broxus/ton-labs-types.git"}
