autogen_warning = "// NOTE: Append the lines below to ios/Classes/<your>Plugin.h"
language = "C"
no_includes = true

[defines]
"target_os = ios" = "TARGET_OS_IOS"
"target_os = macos" = "TARGET_OS_MACOS"
